### ISSUE TITLE
Server doesn't start without elan

### ISSUE THREAD

**Issue by Kha** [leanprover/vscode-lean4#164]
It looks like the extension doesn't start a `lean` in PATH anymore if `elan` doesn't exist AND there is no toolchain file: https://github.com/leanprover/vscode-lean4/blob/49a2e1bcc8e21c372c5a904913c1a7616bb20950/vscode-lean4/src/utils/leanInstaller.ts#L47-L59

This looks unnecessarily restrictive, the `!hasElan` case could be handled by the existing `found.error` case below such that no installation options dialog is shown as long as `checkLeanVersion` succeeds.

**Comment by lovettchris** [comment]
I was told that "elan link toolchain name path" was so easy to setup that we didn't really need to support this case any more.  Properly supporting it would mean adding unit tests for it and so on - do we really need it?

**Comment by Kha** [comment]
Apart from Nix, which I don't demand anyone to care about, this is also somewhat important for setups such as in https://github.com/Kha/do-supplement/blob/master/README.md#exploring-the-supplement-with-lean where we really don't want to impose installing elan on anyone. In fact I didn't realize until now that the artifact instructions have been broken.

**Comment by lovettchris** [comment]
Ah, but surely this is even simpler now: https://www.youtube.com/watch?v=yZo6k48L0VY, much simpler than the instructions in https://github.com/Kha/do-supplement/blob/master/README.md#exploring-the-supplement-with-lean.

**Comment by Kha** [comment]
...except for the "minimizes changes to the host machines" part...

**Comment by lovettchris** [comment]
because it puts something in ~/.elan ?  I don't really consider that intrusive.  I consider installing Visual Studio intrusive :-) elan is light and small and no dependencies, no auto-update service running in the background, now google analytics.  It's fine.

**Comment by Kha** [comment]
I was mostly thinking of editing the shell startup scripts, which isn't easily reversible even if we had an uninstaller. We still do that even when installing elan from VS Code, no? Which is the correct thing to do in general, but it still felt "not nice" to do to reviewers that may want to use Lean exactly once.

**Comment by lovettchris** [comment]
vscode does not edit any startup scripts (on linux) or edit any system environment variables to add lean to the PATH.  It leaves that up to the user.  vscode finds lean in ~/.elan/toolchains and sets the PATH of the local vscode process so that the lean --server works.  But if the user then opens a terminal window and types "lean --version" it is possible that will not work if they user has not also edited their PATH environment.  

But getting back to this issue, I suppose vscode could do a quick lookup to see if lean (and lake) are already in the PATH and actually "work" that it could skip the elan install and use that version of lean instead.... I'll put a PR together and then we can decide how maintainable this is....

**Comment by lovettchris** [comment]
Ok, I checked Ubuntu in my WSL environment and it works there also:

![image](https://user-images.githubusercontent.com/18707114/176984001-061bb72e-9fc3-4d5c-b3cc-68117ddc20b6.png)

So turns out the code you highlighted in the beginning of this issue is only executed if you are running lean adhoc, not in a "package folder" that has a lean-toolchain file.  The above folders that I opened all had a lean-toolchain file, so that is the workaround for now...

**Comment by lovettchris** [comment]
Ok, see [PR#](https://github.com/leanprover/vscode-lean4/pull/208)
