### ISSUE TITLE
Test failures on Windows with `Infoview missing "$TEXT"`

### ISSUE THREAD

**Issue by Vtec234** [leanprover/vscode-lean4#220]
I am making a new issue in order not to revive the zombie thread, but I think this is the same problem as we saw initially in #170. For example, compare [this old run](https://github.com/leanprover/vscode-lean4/runs/6091186060?check_suite_focus=true) linked there with a [freshly failed one](https://github.com/leanprover/vscode-lean4/runs/7328574641?check_suite_focus=true).
 Some observations:
- It seems to happens mostly (only?) on Windows.
- We always see the messages
```
Waiting for InfoView...
InfoView is open.
>>> infoview missing "4.0.0-nightly-"
                <div id="react_root"><p>Waiting for Lean server to start...</p></div>
                ...
```

The message seems to suggest that the tests fail to wait until the Lean server has started. I am not familiar with the code, but perhaps it's a bug in [`waitForInfoViewHtml`](https://github.com/leanprover/vscode-lean4/blob/031cde0791c7fe2cc42427864e01b949fde071e7/vscode-lean4/test/suite/utils/helpers.ts#L204), or at least in the fact that calls to this are not guarded by a wait-for-server procedure.

**Comment by lovettchris** [comment]
Right, this is a new test, I added a "bootstrapping" test that actually installs elan and lean nightly and a stable build of lean and sometimes the Windows machine is timing out - even with a whopping 600 second timeout.  It should never take that long.  This is why I want to merge https://github.com/leanprover/vscode-lean4/pull/218 so that I can see more timing information during test running.  In 218 you can see that normally on windows this test installs elan in about 20 seconds and the stable build in about 10 seconds.  So I'm not sure what is happening yet.  Perhaps there's a product bug that sometimes it fails to initialize the infoview after installing Lean for the first time, but I've never seen this happen on my windows dev box, where I've run the test many times after wiping the .elan folder and it passes every time.

```
8:41:05 PM - Installing Lean via Elan during testing
8:41:08 PM - Wait for elan install of Lean nightly build...
8:41:28 PM - Adding client for workspace: untitled:
...
8:41:31 PM - Wait for lean stable build to be installed...
8:41:31 PM - selectToolchainForActiveEditor: leanprover/lean4:stable
8:41:44 PM - child process exited with code 0
```

**Comment by Vtec234** [comment]
Right, so that will help fix the issue underlying the "waiting for server to start..", but what I'm suggesting is that the tests should detect when the server has not started and not event attempt to look for HTML strings in that case. We could have a timeout so that the test fails if server doesn't start within X seconds. It would make the output a bit clearer.

**Comment by lovettchris** [comment]
This is the timeout that fails the test when the server doesn't restart with X seconds.  But the test only knows that the server started by monitoring the contents of the infoview.  I suppose the test could check LeanClient for the current active editor and find out what state it is in, if it is in a "running" state, but the infoview still says "waiting for server to start..." then we have found a bug in the extension, somehow it failed to update the infoview when the lean server entered the running state... if that's what's going on here (which is my guess, but have not confirmed that).

**Comment by lovettchris** [comment]
Sometimes [tests are randomly failing ](https://github.com/leanprover/vscode-lean4/runs/7331799105?check_suite_focus=true) for a different reason:

The infoview gets stuck showing this message, instead of the real program output:

![image](https://user-images.githubusercontent.com/18707114/178862123-293fc41a-4394-454c-b7b3-66a286d10974.png)

I tried updating the lakefile.lean files to the new format, but that doesn't work either because I'm also testing select toolchain overrides which switch to the "stable" lean build which can't yet handle the new format!

**Comment by Vtec234** [comment]
I'd say it's fine to just disable testing `stable` for now. It is permanently really outdated. It would make sense to reenable it after the first official release of Lean 4, when presumably things will break less often.

**Comment by lovettchris** [comment]
Done: https://github.com/leanprover/vscode-lean4/pull/218/commits/7cb24b291effcfd6f4272ccc59de4ab5c9b1e490

**Comment by lovettchris** [comment]
Hmmm, the bootstrap test is still failing on Windows...
I reproduced it once on my machine and saw this in the output:

```
06:56:36.971 - Wait for elan install of Lean nightly build...
Unexpected token A in JSON at position 0
Unexpected token A in JSON at position 0
```
What JSON? Is that an LSP parsing issue perhaps? And it was completely hosed, not even Restart Server would fix it.  The only time I've been able to reproduce it is with `npm run test` with a completely clean install of .vscode-test, which is installing the latest version of vscode version 1.69.1.   I have not been able to reproduce it in the test debugger.

**Comment by lovettchris** [comment]
the tests have been passing pretty well lately.

**Comment by Vtec234** [comment]
That's not true. The three latest builds failed two of them with "Infoview missing" - [here](https://github.com/leanprover/vscode-lean4/runs/7505275068?check_suite_focus=true) and [here](https://github.com/leanprover/vscode-lean4/runs/7529352417?check_suite_focus=true).

**Comment by lovettchris** [comment]
Flakiness in "Test lean-toolchain edits" is fixed in PR https://github.com/leanprover/vscode-lean4/pull/195/

**Comment by Vtec234** [comment]
Gotcha! Looks like it succeeded after merging that, hopefully it does not come back.
