### ISSUE TITLE
Lean3 vs Lean4 VS code extension

### ISSUE THREAD

**Issue by lovettchris** [leanprover/vscode-lean4#253]
The python extension supports all version of Python.  Can we merge these 2 extensions so users only install one and we only have to update one ?

**Comment by Vtec234** [comment]
As far as I can tell, the community's intention is that once mathlib moves to Lean 4, Lean 3 will reach something like an EOL period where it is no longer receiving updates or supported. From that point of view, it seems better to wait rather than add Lean 3 features which are marked for deprecation to vsc-lean4. What do others think?

**Comment by mhuisi** [comment]
The Lean 3 VS Code extension repository has been archived now.
