### ISSUE TITLE
Goal state updates need debouncing

### ISSUE THREAD

**Issue by Vtec234** [leanprover/vscode-lean4#257]
https://user-images.githubusercontent.com/13901751/194969362-c11be3bf-f063-4fbd-9cf1-1bda57e4d213.mp4

See the video above and note how after I finish typing, the infoview has to churn through 18s (!!) of intermediate states before showing the current goal state. I haven't yet investigated why this happens, but I am assuming it is a consequence of the fact that we eagerly fetch and display new goal states without waiting for the user to finish typing (doing this is known as *debouncing*). We should add debouncing, probably with a user-configurable debounce period (the tradeoff is that waiting can also delay the display of up-to-date info). I will give implementing this a go, but if it's not done in two-ish weeks feel free to poke me.

Note also that the issue is more observable on debug builds, and even more on debug builds over remote SSH setups (which is what I used to record this).

**Comment by gebner** [comment]
What is your setting for elaboration delay?  Another reason for this avalanche of updates is that the server queues requests until the delay is over IIRC.

**Comment by Vtec234** [comment]
@gebner it's the default 200ms. Note that when a pending edit is being accumulated and we receive a new edit, the watchdog responds to all now-outdated messages with `contentModified`. So I don't think we should be seeing this cascade from the server. I might be wrong though?

**Comment by lovettchris** [comment]
There is a queue in WorkerState called `pendingRequests`, what if that queue did some consolidation of redundant requests, like requests for "$/lean/plainGoal"  and "$/lean/plainTermGoal".  This might keep the extension code simpler, and ensure updates to infoview happen as fast as possible without needing imperfect delays.

**Comment by Vtec234** [comment]
> what if that queue did some consolidation of redundant requests

Do you have an idea of how we could consolidate? I thought about this, but I can't see any obvious metric by which to consolidate. The only input parameters to `plainGoal/plainTermGoal` are `TextDocumentPositionParams`, with two fields - the URI and the position. In principle, if we receive two requests for the same position, we could only reply to the first one. *However*, pins really mess up any such heuristic because if we have a pin at position A and the current cursor is *also* on A, both requests are legitimate (different `<Info>` components) and should be replied to. Even ignoring requests received after a new `textEdit` is not legitimate because you can go to A, pin, and pause it, and the displayed goal state *should* be an outdated one.

**Comment by Vtec234** [comment]
I identified part of the issue to be [here](https://github.com/leanprover/vscode-lean4/commit/e1aa3314099fee25e23c5f138306c71d13cd07a1#diff-0148e5f3637b7cbaf7c943678564e19abf2a8d27fe34d865c26e48548fef028bR396). Since `lspDiags` is now a dep of the entire `triggerUpdate` function, we make a number of requests for the (same!) goal state roughly linear (roughly because there is a rate limit on the `triggerUpdate` frequency) in the number of diagnostics appearing lower down in the file. So typing a single character can cause an arbitrary amount of `plainGoal` requests to be sent.

**Comment by gebner** [comment]
> the infoview has to churn through 18s (!!) of intermediate states before showing the current goal state.

After carefully rewatching the video, I think your analysis is wrong about this part.  There are two different things happening in the infoview:
 1. 18 updates to the "all messages" component.
 2. The two updates (first is the diff highlighting, the second is the text) to the info component.

The infoview does both of these updates concurrently, they are completely independent and do not wait for each other.  In fact, the info component already makes sure that there is only a single in-flight update for the goal, and also rate-limits the updates as you've noticed.

However, the "all messages" component is completely dumb.  It updates whenever it receives a new `publishDiagnostics` notification from the server.

So, here's my theory on what's happening:
 - The server queues the `publishDiagnostics` notifications while accumulating edits.
 - Once editing stops, all of these notifications are sent to the client.
 - Since you're connecting over SSH and have a lot of notifications, this probably takes longer than locally.  (Note that the whole notification is shipped to the infoview.)
 - The all messages count updates as these notifications come in.
 - The goal state is actually debounced the way you want it.
