### ISSUE TITLE
Display a warning if "lean4.toolchainPath" is set?

### ISSUE THREAD

**Issue by semorrison** [leanprover/vscode-lean4#326]
The VSCode setting `lean4.toolchainPath` is a [recipe for disaster](https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/.E2.9C.94.20pre-built.20release.20assets.20for.20windows/near/391917793), and only expert users should ever touch it (and even then there are better mechanisms).

Could the extension prominently warn if this is set (a dialog? a prominent warning in the bottom bar?).

**Comment by digama0** [comment]
At least restoring the [warning from lean 3](https://github.com/leanprover/vscode-lean/blob/1589ca3a65e394b3789409707febbd2d166c9344/package.json#L25) seems prudent.

**Comment by mhuisi** [comment]
If we do intend to keep it (and I'm still not sure if this is really necessary given that `elan override` exists), a one-time popup when starting VS Code and perhaps a status bar warning seem like a good way to warn users. The former is necessary because I suspect many users rarely look at the status bar.

**Comment by semorrison** [comment]
I would really prefer to remove this in favour of `elan override`. There's too many ways to do the same thing.
