### ISSUE TITLE
RFC: `cmd-shift-x` opens the extensions sidebar

### ISSUE THREAD

**Issue by semorrison** [leanprover/vscode-lean4#336]
### Proposal

Currently in VSCode we need to hit `cmd-shift-x`, to force of rebuild of stale dependencies of a file.

Unfortunately if you have the left bar open (e.g. the file explorer), then `cmd-shift-x` is captured by opening the extensions side bar. To get around this you need to make sure it click back into an editor window.

Multiple times a day I get this wrong!

Questions:
* Does this impact Linux and Windows users?
* Is there a better fix than just switching to a different keybinding?

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others benefit from the changes in this proposal being added, please ask them to add :+1: to it.

**Comment by mhuisi** [comment]
> Does this impact Linux and Windows users?

Yes, it does.

> Is there a better fix than just switching to a different keybinding?

I'd suggest that we support two separate keybindings for a while, one being the old one.

**Comment by mhuisi** [comment]
@semorrison Note also that changing the keybinding will only alleviate the fact that the extensions sidebar is opened, not that you have to focus an editor window. We need to determine which file to restart somehow, and that unfortunately requires focusing a tab, even if VS Code displays the tab as the currently active one while it is not focused.

**Comment by mhuisi** [comment]
Some additional thoughts on this:

- For the keybinding to work correctly when focusing the sidebar, we need to get rid of the `editorLangId == lean4` condition
- After getting rid of the condition, the command will *always* (even when not in a Lean 4 context) subsume all other keybindings, which is generally undesirable because it is overly invasive
- We could potentially introduce a custom trigger condition that limits when the command triggers, making it less invasive
- In order to make the command work correctly when focusing e.g. the infoview or a terminal, we need to replace the notion of `window.activeTextEditor` with some custom notion of "last active text editor"

**Comment by semorrison** [comment]
Having a key binding that worked everywhere would be perfect, but I would **much** rather have relative to the status quo a key binding that does the right thing *somewhere*, and nothing elsewhere.

The bad user experience here is coming from this frequently used key binding doing "the wrong thing" sometimes.

**Comment by mhuisi** [comment]
@semorrison This should be resolved as of #347. Please let me know if the new release sufficiently resolves this issue - I haven't implemented the version that works everywhere yet.

**Comment by semorrison** [comment]
Confirmed, it works beautifully!
