### ISSUE TITLE
The "Install Lean" button mentions Elan, but users may not know what this is

### ISSUE THREAD

**Issue by david-christiansen** [leanprover/vscode-lean4#352]
### Description

When opening the VS Code extension for the first time, it will offer to install Lean. The button is labeled "Install using Elan", but I fear that the people most likely to want to click that button won't have any idea what Elan is, and it will be confusing, resulting in negative feelings.

Perhaps the button label should simply say "Install"?

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/vscode-lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

**Comment by Kha** [comment]
If we want to keep a reference to Elan so new users at least know the name, we should probably add "using Elan, the Lean version manager" so they can connect that new name to its function

**Comment by david-christiansen** [comment]
That would work, as would a little message under the button like "Installation uses Elan, the Lean toolchain manager". But is this really something users need to know at this time, at the risk of confusion? It's a tiny detail, but lots of tiny details are what add up to a nice experience.

**Comment by tydeu** [comment]
Since users who install Lean using this method are users who, in the ideal circumstances, never have to touch Elan directly, I agree that a simple "Install" seems preferable. The best place for them to Learn about it later is problem in tutorial guides that outline the standard project directory and link to a more detailed description if users want to learn more about how the `lean-toolchain` file works.
