### ISSUE TITLE
Output channel is opened when vscode is started

### ISSUE THREAD

**Issue by gebner** [leanprover/vscode-lean4#65]
Whenever I open a new vscode instance, the nLean 4 extension opens the output channels and prints the Lean version.  It is annoying to close it every time.  I believe this is a regression from #35.

**Comment by lovettchris** [comment]
It was deliberate, because sometimes `lean --version` take a long time while it is installing a new version of lean and the output window tells the user what is happening.  Unfortunately there's not really any easy way for the vscode extension to know when `lean --version` is going to take a long time...

**Comment by Vtec234** [comment]
Could we use a "Starting Lean.." (or some such) [progress notification](https://code.visualstudio.com/api/references/extension-guidelines#progress-notification) instead? Ideally we would only show the output channel when there are errors that users should report to us, otherwise it is a little bit tedious to have to close it every time (and on most startups the right version will already have been installed).
