### ISSUE TITLE
Yellow bar doesn't disappear when there are invalid imports.

### ISSUE THREAD

**Issue by semorrison** [leanprover/vscode-lean4#67]
Steps to reproduce:

Create a new `foo.lean` file in VSCode, and `import bar` (without having created a `bar.lean`).

There is a red squiggle under `import bar` saying `unknown package 'bar'`, but the yellow bar (and the pop-up message "busily processing") never disappears.

Expected:

The yellow bar should disappear if nothing further is going to change, regardless of how successful processing the file was!

**Comment by Kha** [comment]
The yellow bar is from the server, so this would have to be changed in leanprover/lean4. I think the intention was that the bar means "not yet processed" instead of "still processing", in which case the behavior is correct. In particular, it upholds the invariant that if a declaration has neither errors nor the bar, it is correct. That seems like a nice invariant? But I've also been misled by the bar before.

**Comment by Kha** [comment]
We could of course turn the bar red (e.g.) if processing is stalled. Also after `#exit`.

**Comment by gebner** [comment]
As Sebastian has already said, this behavior is very much intentional.  The orange bar means "don't trust the absence of error messages".  Think of opening a file in the middle and wondering why Lean accepts `theorem important : false := trivial` without error.  As per my explanation on the [original PR](https://github.com/leanprover/lean4/issues/503):

> This feature is useful because it allows you to tell at a glance whether a definition was accepted without error or is still being elaborated.

I think Sebastian's suggestion of changing the bar color is very reasonable.  Several users got the idea that orange bars = 100% CPU, even though that was never the intention.  Maybe a different color could make it clear that there are several reasons why the bars are still there.

**Comment by semorrison** [comment]
Often if I'm expecting Lean to take a while to catch up, I may simply not look at file until the yellow bars have gone away. That is, my interpretation of yellow bars has historically always been "still processing", and this is the first time I've heard the idea that it might be "not yet processed"! I guess that could be okay, but I suspect we'll have to retrain everyone from their Lean3 expectations.
