### ISSUE TITLE
Infoview doesn't show errors when lake fails

### ISSUE THREAD

**Issue by gebner** [leanprover/vscode-lean4#90]
If you have two files like this:
```lean
-- A.lean
does not compile

-- B.lean
import A
```

And put the cursor on the first line of `B`, then the infoview doesn't show the error diagnostic for the import error.  (Presumably because we also request interactive diagnostics, and treat the resulting error as "no messages found").

**Comment by lovettchris** [comment]
@gebner - interesting, I see a red squiggly on import A and the tool tip matches what you see below, this message flashes real quick in the infoview then it disappears.

![image](https://user-images.githubusercontent.com/18707114/149026744-5df543d1-76be-4e03-b127-d8696e3caf41.png)

and I think it is because the call to 'Lean.Widget.getInteractiveDiagnostics' returns [] which clears the infoview.  So the infoview must be showing the red squiggle info first, then calls getInteractiveDiagnostics and that wipes the message.  Is this a Lean LSP bug ?

**Comment by marianaalanis93** [comment]
I was able to reproduce this issue. I will check the possible solution.

**Comment by gebner** [comment]
> Is this a Lean LSP bug ?

In some sense, maybe.  I guess you could argue that they are not "real" Lean diagnostics, and `getInteractiveDiagnostics` should only return diagnostics created by the Lean compiler.  In either case, this part of the RPC API is underspecified.

**Comment by leodemoura** [comment]
@gebner Is it clear to you what needs to be done to address this issue?

**Comment by gebner** [comment]
Yes, I just need to close it. :smile:  Mariana fixed this in #173.
